---
- name: create directory
  hosts: localhost
  tasks:
    - name: directory
      file:
        path: /tmp/www
        state: directory
        owner: www-data
        group: www-data
        mode: 0775
      register: file
    - debug:
            var: file
