---
- name: Fill motd file with host data
  hosts: localhost
  tasks:
    - template:
        src: "../templates/motd-facts.j2"
        dest: "/etc/motd"
        owner: root
        group: root
        mode: 0644
