---

 - name: create directory and update shell scripts.
   directory:
     path: /root/cron
     state: present
     mode: 0755
   register: path_out

 - name: template a file to /root/crons/cpu_mem.sh
   ansible.builtin.template:
     src: ../templates/syssts.j2
     dest: /root/cron/cpu_mem.sh
     mode: 0755

 - name: script schedule
   become: true
   shell:
     /root/cron/cpu_mem.sh
   register: output

 - name:
   debug:
     var: path_out, output
